spring:
  application:
    name: transaction-service
  data:
    mongodb:
      database: Transaction
      host: mongo-container
      port: 27017
server:
  port: '8083'

eureka:
  client:
    instance:
      preferIpAddress: 'true'
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka