spring:
  application:
    name: zuul-service
server:
  port: '8080'

eureka:
  client:
    instance:
      preferIpAddress: 'true'
    fetchRegistry: 'true'
    registerWithEureka: 'true'
    serviceUrl:
      defaultZone: http://172.21.0.2:8761/eureka

zuul:
  routes:
    account:
      path: /account/**
      serviceId: account-service
    statement:
      path: /statement/**
      serviceId: statement-service
    transaction:
      path: /transaction/**
      serviceId: transaction-service

  instance:
    statusPageUrl: http://172.21.0.2:8761/actuator
    healthCheckUrl: http://172.21.0.2:8761/actuator/health
    homePageUrl: http://172.21.0.2:8761
    nonSecurePortEnabled: true
    preferIpAddress: false